import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#282a36',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingTop: 60, 
  },
  clockTitle: {
    fontSize: 65,
    letterSpacing: 10,
    color: '#bd93f9',
    shadowOpacity: 0.5,
  },
  dateInfo: {
    fontSize: 20,
    color: '#fff',
  },
  clockInfo: {
    width: '70%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'white',
    overflow: 'hidden',
    backgroundColor: '#44475a',
    fontSize: 48,
    color: '#fff',
    letterSpacing: 5,
  },
  buttonWrapper: {
    flex: 0.06,
    width: '55%',
    marginTop: 5,
    backgroundColor: '#44475a',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'gray',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  mainTimer: {
    flex: 0.45,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    width: '75%',
    marginTop: 35,
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: 'white',
    backgroundColor: '#44475a',
  },
  timerStatus: {
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#bd93f9',
    flex: 0.3,
    textAlign: 'center',
    fontSize: 35,
    letterSpacing: 4,
    color: '#bd93f9',
    fontWeight: '300',
  },
  balance: {
    fontSize: 15,
    color: 'white',
  },
  alarmName: {
    padding: 10,
    flex: 0.3,
    textAlign: 'center',
    fontSize: 42,
    color: '#f1fa8c',
  },
  alarmDetails: {
    padding: 10,
    flex: 0.8,
    fontSize: 20,
    color: '#f1fa8c',
  },
  alarmTab: {
    flexDirection: 'row',
    flex:0.28,
  },
  alarmTabButtons: {
    width: 40,
    height: 40,
    backgroundColor: '#44475a',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'white',
    justifyContent: 'center',
    alignContent: 'center',
  },
});
